[project]
name = "voicemail-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "pydub>=0.25.1",
    "speechrecognition>=3.14.2",
    "streamlit>=1.44.1",
]
